name: Django CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:  [3.9]
    steps:
      - name: activate env
        uses: JimCronqvist/action-ssh@master
        with:
          command: source venv/bin/activate
          hosts: ${{ secrets.HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
      - name: pull last code
        uses: JimCronqvist/action-ssh@master
        with:
          command: cd cicdlecture; git pull
          hosts: ${{ secrets.HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
      - name: collect static
        uses: JimCronqvist/action-ssh@master
        with:
          command: python manage.py collectstatic --no-input
          hosts: ${{ secrets.HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
      - name: restart services
        uses: JimCronqvist/action-ssh@master
        with:
          command: sudo systemctl restart gunicorn; sudo systemctl restart nginx
          hosts: ${{ secrets.HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
